<<<<<<< HEAD
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

=======
>>>>>>> Added CI pipeline definition
trigger:
  - main

pool:
  name: Default
  demands:
    - agent.name -equals self-hosted-agent


steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1

  - script: dotnet build
    displayName: 'Build Project'

  - script: dotnet pack --configuration Release -o $(Build.ArtifactStagingDirectory)
    displayName: 'Pack NuGet Package'

  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: 'Azure Artifacts Feed'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      publishVstsFeed: 'StringExtensionsFeed'
<<<<<<< HEAD

=======
>>>>>>> Added CI pipeline definition
