# Corrected azure-pipelines.yml
trigger:
  - main

pool:
  name: Default
  demands:
    - agent.name -equals self-hosted-agent

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1

  - script: dotnet build
    displayName: 'Build Project'

  - script: dotnet pack --configuration Release -o $(Build.ArtifactStagingDirectory)
    displayName: 'Pack NuGet Package'

  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: 'AzureNugetArtifactFeed'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      publishVstsFeed: 'StringExtensionsFeed'
